name: Docker Build/Publish Image

on:
  push:
    branches: [ develop ]
    
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE: filleellif/marp.shop
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      run: |
        docker buildx build --platform linux/arm/v7 --tag marp.shop:latest --output "type=image,push=false" .
